# Generated by Django 4.1.2 on 2022-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_demos', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
